# Generated by Django 3.2.4 on 2021-06-12 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='link',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
