# Generated by Django 3.2.4 on 2021-06-12 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0003_teams'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Teams',
            new_name='Team',
        ),
    ]
